name: TB Analytics Custom Image CI

on:
  push:
    branches:
      - main
    tags:
      - '*'


env:
  PROJECT_ID: phx-01h7gg8s1qfey7gw6ryqjrxtxe
  REGION: northamerica-northeast1
  ARTIFACT_REGISTRY: northamerica-northeast1-docker.pkg.dev/phx-01h7gg8s1qfey7gw6ryqjrxtxe/tb-project

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    
    - name: Hadolint Action
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./analytics-environment/Dockerfile
        
    - name: "Set image name"
      run: |
        echo "IMAGE_NAME=$ARTIFACT_REGISTRY/tb-env" >> $GITHUB_ENV
        
    - name: Build an image from Dockerfile
      working-directory: analytics-environment
      run: |
          docker build -t $IMAGE_NAME .
          
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
  trigger-cloud-build:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.event.ref_type == 'tag'
    steps:   
    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"
    - name: "Use gcloud CLI"
      run: "gcloud info"
    - name: "Extract tag name"
      id: extract-tag
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
    - name: "Trigger cloud build"
      run: |-
        gcloud builds triggers run --region=$REGION --tag==${{ steps.extract-tag.outputs.tag }} tb-env-build
