name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: phx-01h7gg8s1qfey7gw6ryqjrxtxe
  REGION: northamerica-northeast1
  ARTIFACT_REGISTRY: northamerica-northeast1-docker.pkg.dev/phx-01h7gg8s1qfey7gw6ryqjrxtxe/tb-project/

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Hadolint Action
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./Dockerfile
        
    - name: "Set image name"
      run: |
        echo "IMAGE_NAME=$ARTIFACT_REGISTRY/tb-env" >> $GITHUB_ENV
        
    - name: Build an image from Dockerfile
      run: |
          docker build -t $IMAGE_NAME .
          
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '$IMAGE_NAME'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        
    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"
    - name: "Use gcloud CLI"
      run: "gcloud info"
    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Push image
      run: docker push $IMAGE_NAME
